### ISSUE TITLE
feature: Add boolean "disabled" attribute to CoreAccount

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3505]
### Component

API Server / GraphQL

### Describe the Feature Request

This attribute should be used to allow for users to be disabled

### Describe the Use Case

When you want to lock out a user without deleting the account

**Comment by dgarros** [comment]
Based on the recent discussion, I propose to implement a status field for the account instead of a flag, this way we'll be able to manage more states, we can start with the easy one 
- Active
- Disabled

Later I can imagine we'll need a state to indicate if an account has been validated or not
- Pending Validation

**Comment by dgarros** [comment]
@gmazoyer can we consider it done after #3980

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/124fdf9282993a0d41388fb2a5131e5f6ad3f618
