### ISSUE TITLE
bug: allocating a resource from a resource pool using the from_pool resolver fails for relationships with cardinality many

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3594]
### Component

API Server / GraphQL

### Current Behavior

When you want to allocate a resource out of a resource pool using the from_pool resolver to a relationship with cardinality many, the GraphQL mutation will fail with an error message "Relationship has not been initialized yet". 

### Expected Behavior

A new resource would be allocated from the resource pool and added as a relationship to the node for which you executed the mutation.

### Steps to Reproduce

- `inv dev.start demo.load-infra-schema demo.load-infra-data`
-  gather the id of the `Loopbacks pool` resource pool
- execute the following GraphQL mutation (replace the id in the from_resource pool resolved to the id you gathered in the previous step)
 ```graphql
 mutation { 
  InfraInterfaceL3Create(data: {
    name: {value: "test2"},
    speed: {value: 1000},
    device: {hfid: "atl1-edge1"}
    ip_addresses: [
      {from_pool: {id: "17d62240-7358-eb69-32c2-c5157f30df8e"}}
    ]
  })
  {
    ok
  }
}
 ```

**Comment by pa-lem** [comment]
another related issue is the mutation to add a relationship, it doesn't handle the from_pool property

for example, this mutation won't work:
```
mutation RelationshipAdd {
  RelationshipAdd(
    data: {
      id: "17d5c0c9-e93a-22b2-3b62-c51ea28df153",
      name: "ip_addresses",
      nodes: [
        {
          from_pool: {
            id: "17d5c0a7-577f-8e93-3b69-c51e621eb9ba"
          }
        }
      ]
    }
  ) {
    ok
    __typename
  }
}
```

because of this error where from_pool is not available
```
Field 'from_pool' is not defined by type 'RelatedNodeInput'.
```

**Comment by dgarros** [comment]
This is a bit more complicated than I thought initially

Currently we are have a specific RelatedNode object per type of pool which allow us to support specific properties per pool under `from_pool`

In order to support resource pool on the mutation `RelationshipAdd` we'll need to take a more generic approach that should work with all kind of pool. We need to take the common attribute between `PrefixPoolInput` and `IPAddressPoolInput`

@gmazoyer please can you take a look, please let me know if you have some questions

**Comment by gmazoyer** [comment]
I think these are two separate issues. The one originaly reported does not come from the pool allocation but from the use of an HFID to reference the device, as we can see in the stack trace:

```
│ /Users/gmazoyer/Development/infrahub/backend/infrahub/core/relationship/model.py:412 in resolve  │
│                                                                                                  │
│    409 │   │   │   del data_from_pool["id"]                                                      │
│    410 │   │   │                                                                                 │
│    411 │   │   │   if "identifier" not in data_from_pool and self._node:                         │
│ ❱  412 │   │   │   │   hfid_str = await self._node.get_hfid_as_string(db=db, include_kind=True)  │
│    413 │   │   │   │   if hfid_str:                                                              │
│    414 │   │   │   │   │   data_from_pool["identifier"] = f"hfid={hfid_str} rel={self.name}"     │
│    415                                                                                           │
```

When using an ID instead of an HFID, the mutation works:

```graphql
mutation { 
 InfraInterfaceL3Create(data: {
   name: {value: "test2"},
   speed: {value: 1000},
   device: {id: "whatever-id-you-have-in-record"}
   ip_addresses: [
     {from_pool: {id: "17d62240-7358-eb69-32c2-c5157f30df8e"}}
   ]
 })
 {
   ok
 }
}
```

So I think we should split this issue into two different ones.

**Comment by pa-lem** [comment]
I created the second one for the RelationshipAdd mutation (https://github.com/opsmill/infrahub/issues/3601)

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/1108903125a34b4df6ef450818de63f0819141b6
