### ISSUE TITLE
feature: Display parent of component in list view

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#3891]
### Component

Frontend UI

### Describe the Feature Request

When displaying all objects of a model that is a component of another model (AKA has a relationship of Kind Parent defined), the parent should be displayed in the list view to properly identify the context around the component.

In the example below coming from the demo schema, the `InfraInterfaceL2` model is a component of `InfraDevice` and without the device name it's difficult to understand which device a given interface belongs to

![Screenshot 2024-07-22 at 13 42 42](https://github.com/user-attachments/assets/59ed5f0c-41e8-47e9-bd78-87672c91c47f)

### Describe the Use Case

Improve the handling of models defined as component of another model in the schema.
 

### Additional Information

When the same objects are displayed in the context of the parent (in a tab as part of the detailed view of the parent), the parent doesn't have to be displayed because would be redundant

![Screenshot 2024-07-22 at 13 46 08](https://github.com/user-attachments/assets/e6cc21b5-892d-446a-8b06-1c689ee8aded)

**Comment by bilalabbad** [comment]
Update:
We need to always display the parent object, except when the current context is the same as the parent object because it will once add noise. Since the schema definition doesn't reliably help in identifying this, to handle all edge cases, we need to fetch all relationship types (except relationships of kind "Component", as they are obviously the same object). After fetching these, we'll filter the columns view accordingly.
