### ISSUE TITLE
bug: object type in create profile form is not displaying the namespace of the original node

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4001]
### Component

Frontend UI

### Infrahub version

0.16.0.dev0

### Current Behavior

The object type drop down form input is not showing the namespace of the schemanode.

Instead it is showing "Profile" twice and the name of the node. Which is confusing when you have 2 schemanodes that have the same node but a different namespace.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/27c4df40-6b31-4bea-8cef-4a4cba804b27">

### Expected Behavior

The namespace of the schemanode is shown in the dropdown

### Steps to Reproduce

- load infrahub
- in the web ui navigate to profiles
- Click `Add Profile`
- The dropdown will show (as example) `Profile Tag Profile`

**Comment by pa-lem** [comment]
Here we are on the generic profile form to create a specific profile node, not an object node

So we have the schemas for all profile nodes, the labels and namespaces are good according to what we have in the schema list for the profiles

I understand that it could be clearer to display label and namespace from the schema of the object node that could implement the selected profile, but the logic won't be consistent to the rest of the forms since here we won't create object nodes, but profile nodes

What do you suggest, to use the schema of the node object that could implement the profile we want to create? Have you considered if it won't be too much confusing to select an object node in the type selector that is not the actual type we are creating? (for example selecting `Interface L2` in the `Infra` namespace, but it's actually a `ProfileInterfaceL2` node we are creating and not a `InfraInterfaceL2`)

I'm not sure yet if we have a clean way to link the profile schema to the node schema, but it could be done one way or another
