### ISSUE TITLE
task: Document the schema.graphl Endpoint

### ISSUE THREAD

**Issue by marcom4rtinez** [opsmill/infrahub#4831]
### Component

Documentation & Examples

### Task Description

Hi,

I think it would be nice to have documented that the GraphQL Schema can be downloaded und /schema.graphl. I had to search the code, as there was nothing in the docs.

`@router.get("/schema.graphql", include_in_schema=False)`

**Comment by ogenstad** [comment]
As of the last version there's a brief mention of it here:
https://docs.infrahub.app/topics/graphql

I'd want us to have some description around how it can be used as well, however I think it would be nice to do some cleanup of the schema in general first as there are some things that we don't really see when using the Python SDK or the frontend but would show up in other situations. This is around changing some requirements so that more fields are required to not be `null` or `None`. For instance if we generate bindings using the current schema in Python a model for tags could include code like this:

```python
# Generated by ariadne-codegen
# Source: queries/sdk/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetTags(BaseModel):
    builtin_tag: Optional["GetTagsBuiltinTag"] = Field(alias="BuiltinTag")


class GetTagsBuiltinTag(BaseModel):
    edges: Optional[List[Optional["GetTagsBuiltinTagEdges"]]]
```

Here the schema defines that edges can be an `Optional` list, which is in fact wrong it should always be a list, but an empty list if no results exist. I.e. according to the schema edges could be either `[]` or `None` if empty. Further the entries in the list aren't optional, either you have an entry or you don't so `[None]` should never happen but can according to the schema.

What is it you wanted to do based on this endpoint? (we can also talk about it it the chat)

**Comment by marcom4rtinez** [comment]
Ah ok, then i might have missed this. I have been experimenting with the Go SDK, where we generate the SDK based on the GraphQL schema. 

In general no use-case in particular, just didnt find it in the documentation, that you can get it using the Endpoint `localhost:8000/schema.graphl` and thought it might be nice to document it, so if others need it they wont have to look it up in the code.

**Comment by marcom4rtinez** [comment]
Therefore i think this can be closed
